spring.application.name=Springboot-basic

spring.dataource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/platzi_play
spring.datasource.username=postgres
spring.datasource.password=123
